# 项目配置信息
app:
  env: dev
  debug: false
  admin_email:
    -
    # 不知道怎么生成的可以看这个网站 http://www.usey.cn/rsa?bits=2048
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1JqqxPLNWEy371X+kOXq
    wE8fMebohqHI9txXRoUIh28dYsrv85JTrknLlPcYWT5Q27nHGcywu8hpsjMwe1U2
    akHikIzLYEu/8GaGqI7qHa+73F54lVKHBcwdK8PjH8+o76kN9MsouJ8QA7Nk0g4u
    6equEzyrchwjr/bOjP4MhPt4hU90jpQbp3tqDu6PQgPQZzxDtIX9TeqzplCAYNy2
    M4i1HtbZk2a9vimFqTsM8i+ALPH47c+Bt4b4mLoKqSyF6K1muhV/kqfecV8fvyfN
    bkJdUkWQnNvgTX0f1nhAshArLMw4VyROrYBAamFgtzwRpC4qCYhBzWqyhb10bEEf
    XwIDAQAB
    -----END PUBLIC KEY-----

  private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDUmqrE8s1YTLfv
    Vf6Q5erATx8x5uiGocj23FdGhQiHbx1iyu/zklOuScuU9xhZPlDbuccZzLC7yGmy
    MzB7VTZqQeKQjMtgS7/wZoaojuodr7vcXniVUocFzB0rw+Mfz6jvqQ30yyi4nxAD
    s2TSDi7p6q4TPKtyHCOv9s6M/gyE+3iFT3SOlBune2oO7o9CA9BnPEO0hf1N6rOm
    UIBg3LYziLUe1tmTZr2+KYWpOwzyL4As8fjtz4G3hviYugqpLIXorWa6FX+Sp95x
    Xx+/J81uQl1SRZCc2+BNfR/WeECyECsszDhXJE6tgEBqYWC3PBGkLioJiEHNarKF
    vXRsQR9fAgMBAAECggEBAIgad8Zbda/YdUwHrk9OkQkJ3fuRSjyeJ8w5ZLnlgn9J
    V/Od3Rz+CQojfevgf7rqFNOFS/utOVsNwvRsptXdyFcf1I4bRDtiYv7gc8ZGr4PP
    s6Ew7VsSmRPSBr60yZrc0taSUDftMyV11se3uYxrvgbL0SLJjSwg7YvBoZtLK/KY
    6u+oAhMALuiOV773+TApKatQrNy41DaB+YNkxQzQbp8lHaLApLLSYkyIn47kxmwh
    qaH3NX13KnWauNYA2HuuZmrVH4nabr8WFq2057vJlssWcxgwxDEEjtkY2GofiHAo
    r+cXslrErX8hpJrQ2S6bVtisqVVib5yhruG7Ke45kOkCgYEA9vnQxF5LqY2TETz0
    1NAPu1mSvPdmM78CwT5uFnjhYDfnf41346Cv/WEDvZJuLwo2LCf+N0qpb/pJ7e0V
    lAhXsJqFSdRgd6GOdImVvuC2meoUQF282neGeRI6SKPCz4r+DRMBbjkIrDSCw/TR
    yB+hPAxxgHKHC4ji3tB9Lzl//y0CgYEA3F9Xv5PFV/A5j0uDK3rOE0frfEWUfxPx
    IUPjaWPbajHQqgJDqJyB6lg2M284FEYGtGlPHZGSU9Q15NEVukmhsZJm2Vzsf6Ss
    8BEAJS7ngtj064h0QYrOwyUHMVC99OdvQTSi5LTQxTYQp0jnxdinFX2NF8zDRdt5
    ePQqi0AYkDsCgYEA9hr2N9enGewj8veFGVPDeXPGz1rQkxvyCNLHLMmD/Dd5DhfQ
    shl7hcfYzF1QQruwQ8wOfNZ/hUApz1eDOyIdD7TKwUlKX6uzotk/SRfvnewuBf3i
    pOiaLadGQQA+rkXY5vpbYJSg2cjxzYb2TK+IIahcqhx2Cb58JIApXpezvnkCgYBL
    Ba5SyxTI3kBKNzPdjn4vdDGH6gwmwvw5DeqSi2s8GN9nsUOlWDqmNAentPpLdJd9
    vcgwUcmV/k2mq0ORWtXQJP4ci5T7020IgVEiV3h7RC8FLDwfwAipyKZNNKamhE+M
    zEWURLY6HTDIMnqtERe4qjhpXM0xsAkHk2AUbequ1wKBgGjV3oF/Pk9i94YhG61P
    +OSFzf6Ci+c6aGz1pWRP6KwTJAnHV/1sI+8uHp6gJZnxiJyPsESqX8whttF36UaC
    en1nf7/FASIbrMbL+vAAxzKPCbo6iBOV9e4MsimgT9Vo7kpsi49VsNCFCriliCja
    k4cC5qJhehEvZcgOiwr5qsvi
    -----END PRIVATE KEY-----

server:
  http: 9501
  websocket: 9502

# 日志配置
log:
  # 日志文件路径 *请使用绝对路径*
  path: "/path/to/.../runtime"

# Redis 相关配置
redis:
  host: 127.0.0.1:6379
  auth: xxx
  database: 0

# Mysql 数据库配置
mysql:
  host: 127.0.0.1
  port: 3306
  charset: utf8mb4
  username: root
  password: xxxx
  database: go_chat
  collation: utf8mb4_general_ci

# Jwt 配置
jwt:
  secret: 836c3fea9bba4e04d51bd0fbcc5
  expires_time: 3600
  buffer_time: 3600

# 跨域配置
cors:
  origin: "*"
  headers: "Content-Type,Cache-Control,User-Agent,Keep-Alive,DNT,AccessToken,Authorization"
  methods: "OPTIONS,GET,POST,PUT,DELETE"
  credentials: false
  max_age: 600

# 文件系统配置【oss,qiniu 暂不支持】
filesystem:
  default: local
  local:
    # 文件保存的根目录
    root: "/path/xx/lumenim/"
    # 公开的 bucket
    bucket_public: "public"
    # 私有的 bucket
    bucket_private: "private"
    endpoint: "im-cdn.xxx.com"
    ssl: false
  minio:
    secret_id: "xxxxxx"
    secret_key: "xxxxx"
    # 公开的 bucket
    bucket_public: "im-static"
    # 私有的 bucket
    bucket_private: "im-private"
    endpoint: "im-cdn.xxx.com"
    ssl: false

# 邮件配置
email:
  host: smtp.163.com
  port: 465
  username: xxxxx
  password: xxxxx
  fromname: "Lumen IM 在线聊天"